symfony_skillbox_homework:
  # Стратегия производства юнитов по умолчанию по силе (SymfonySkillbox\HomeworkBundle\StrengthStrategy)
  # Стратегия производства юнитов по силе (symfony_skillbox_homework.strategy_health)
  strategy: symfony_skillbox_homework.strategy_health
  # Разрешено лHomeworkи производство солдат
  enable_solder: true
  # Разрешено ли производство лучников
  enable_archer: true


